---
- name: Add bootstrap instances
  add_host:
    name: "{{ hostvars[item].gce_name }}"
    groups:
    - bootstrap
    - nodes
    openshift_ignition_file_path: "{{ openshift_bootstrap_ignition_file }}"
  with_items: "{{ groups['tag_ocp-bootstrap'] | default([]) }}"

- name: Add master instances
  add_host:
    name: "{{ hostvars[item].gce_name }}"
    groups:
    - masters
    - nodes
  with_items: "{{ groups['tag_ocp-master'] | default([]) }}"

- name: Add worker instances
  add_host:
    name: "{{ hostvars[item].gce_name }}"
    groups:
    - workers
    - nodes
  with_items: "{{ groups['tag_ocp-worker'] | default([]) }}"

- name: Add new worker instances
  add_host:
    name: "{{ hostvars[item].gce_name }}"
    groups:
    - new_workers
    - nodes
  with_items: "{{ groups['tag_ocp-new-worker'] | default([]) }}"
