#!/bin/sh

# This launches the Kubelet by converting the node configuration into kube flags.

set -euo pipefail

if ! [[ -f /etc/origin/node/client-ca.crt ]]; then
  if [[ -f /etc/origin/node/bootstrap.kubeconfig ]]; then
    oc config --config=/etc/origin/node/bootstrap.kubeconfig view --raw --minify -o go-template='{{ index .clusters 0 "cluster" "certificate-authority-data" }}' | base64 -d - > /etc/origin/node/client-ca.crt
  fi
fi
config=/etc/origin/node/bootstrap-node-config.yaml
# TODO: remove when dynamic kubelet config is delivered
if [[ -f /etc/origin/node/node-config.yaml ]]; then
  config=/etc/origin/node/node-config.yaml
fi
flags=$( /usr/bin/openshift-node-config "--config=${config}" )

sysconfig=/etc/sysconfig/origin-node
if [[ -f /etc/sysconfig/atomic-openshift-node ]]; then
  sysconfig=/etc/sysconfig/atomic-openshift-node
elif [[ -f /etc/sysconfig/origin-node ]]; then
  sysconfig=/etc/sysconfig/origin-node
fi
hostname_override=$(sed -nE 's|^HOSTNAME_OVERRIDE=([^#].+)|\1|p' "${sysconfig}" | head -1)
if [[ ! -z "${hostname_override}" ]]; then
  flags="$flags --hostname-override=\"$hostname_override\""
fi
eval "exec /usr/bin/hyperkube kubelet --v=${DEBUG_LOGLEVEL:-2} ${flags}"
